//! Kernel-checked route: a self-contained `Check.lean` that embeds the models
//! and certificates and proves `checkCertificate model cert = true` by
//! `decide`, then `#print axioms` for the audit.

use anyhow::{bail, Context, Result};
use mulu_model::core::CoreModel;
use serde_json::Value;
use std::path::Path;
use std::process::Command;

pub const ALLOWED_AXIOMS: &[&str] = &["propext", "Quot.sound", "Classical.choice"];

pub fn ident(s: &str) -> String {
    let mut out = String::new();
    for c in s.chars() {
        if c.is_ascii_alphanumeric() || c == '_' {
            out.push(c);
        } else {
            out.push('_');
        }
    }
    if out.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(true) {
        out.insert(0, '_');
    }
    out
}

fn nat_list(v: &[usize]) -> String {
    let items: Vec<String> = v.iter().map(|n| n.to_string()).collect();
    format!("[{}]", items.join(", "))
}

fn edge_list(edges: &[[usize; 3]]) -> String {
    let items: Vec<String> = edges.iter().map(|e| format!("⟨{}, {}, {}⟩", e[0], e[1], e[2])).collect();
    format!("[{}]", items.join(", "))
}

pub fn plant_def(name: &str, m: &CoreModel) -> String {
    format!(
        "def {name} : Plant where\n  numStates := {}\n  numEvents := {}\n  controllable := {}\n  initial := {}\n  marked := {}\n  bad := {}\n  edges := {}\n",
        m.num_states,
        m.num_events,
        nat_list(&m.controllable),
        nat_list(&m.initial),
        nat_list(&m.marked),
        nat_list(&m.bad),
        edge_list(&m.edges)
    )
}

fn json_nats(v: &Value) -> Vec<usize> {
    v.as_array().map(|a| a.iter().filter_map(|x| x.as_u64().map(|n| n as usize)).collect()).unwrap_or_default()
}

fn json_edges(v: &Value) -> Vec<[usize; 3]> {
    v.as_array()
        .map(|a| {
            a.iter()
                .filter_map(|e| {
                    let n = json_nats(e);
                    (n.len() == 3).then(|| [n[0], n[1], n[2]])
                })
                .collect()
        })
        .unwrap_or_default()
}

/// Lean term for a certificate JSON (the worker's format).
pub fn cert_term(c: &Value) -> Result<String> {
    Ok(match c["kind"].as_str().unwrap_or("") {
        "reachability" => format!(".reachability {}", nat_list(&json_nats(&c["states"]))),
        "redundancy" => format!(
            ".redundancy {} ⟨{}, {}, {}⟩",
            nat_list(&json_nats(&c["states"])),
            c["check"]["id"],
            c["check"]["pass_event"],
            c["check"]["fail_event"]
        ),
        "unreachable-check" => format!(
            ".unreachableCheck {} ⟨{}, {}, {}⟩",
            nat_list(&json_nats(&c["states"])),
            c["check"]["id"],
            c["check"]["pass_event"],
            c["check"]["fail_event"]
        ),
        "violation" => format!(".violation {}", edge_list(&json_edges(&c["path"]))),
        "envelope" => {
            let chain: Vec<String> = c["chain"].as_array().map(|a| a.iter().map(|w| nat_list(&json_nats(w))).collect()).unwrap_or_default();
            format!(".envelope {} [{}]", c["nonblocking"].as_bool().unwrap_or(true), chain.join(", "))
        }
        k => bail!("unknown certificate kind {k:?}"),
    })
}

pub struct CertEntry<'a> {
    pub id: &'a str,
    pub model: &'a str, // Lean name of the plant definition
    pub cert: &'a Value,
}

pub fn generate(models: &[(&str, &CoreModel)], certs: &[CertEntry], model_hash: &str) -> Result<String> {
    let mut s = String::new();
    s.push_str("import Mulu\n");
    // The envelope certificate for a model of any size is a large term, and
    // `decide` unfolds it in the kernel. Without a raised limit the check
    // fails with a recursion error, which the axiom audit then sees as
    // `sorryAx`; the claim is refused rather than believed, but the answer
    // is lost. Raising the limit does not weaken the check.
    s.push_str("set_option maxRecDepth 1000000\n");
    s.push_str("/-!\nGenerated by mulu. Do not edit: `mulu verify` regenerates this file and\n");
    s.push_str("rejects any difference. Each theorem is checked by the Lean kernel (`decide`).\n");
    s.push_str(&format!("model sha256: {model_hash}\n-/\nopen Mulu.Core Mulu.Analysis\n\n"));
    for (name, m) in models {
        s.push_str(&plant_def(name, m));
        s.push('\n');
    }
    for c in certs {
        let id = ident(c.id);
        s.push_str(&format!("def cert_{id} : Certificate := {}\n", cert_term(c.cert)?));
        s.push_str(&format!("theorem cert_{id}_ok : checkCertificate {} cert_{id} = true := by decide\n", c.model));
        s.push_str(&format!("#print axioms cert_{id}_ok\n\n"));
    }
    Ok(s)
}

pub struct KernelResult {
    pub ok: bool,
    pub log: String,
    pub axioms: Vec<(String, Vec<String>)>,
    pub bad_axioms: Vec<String>,
}

/// Run `lake env lean Check.lean` in the Lean project and audit axioms.
pub fn run_kernel(lean_dir: &Path, check_file: &Path) -> Result<KernelResult> {
    let out = Command::new("lake")
        .arg("env")
        .arg("lean")
        .arg(check_file.canonicalize()?)
        .current_dir(lean_dir)
        .output()
        .with_context(|| "running `lake env lean` (is `lake` on PATH?)")?;
    let log = format!("{}{}", String::from_utf8_lossy(&out.stdout), String::from_utf8_lossy(&out.stderr));
    let mut axioms = vec![];
    let mut bad = vec![];
    for line in log.lines() {
        if let Some(rest) = line.strip_prefix('\'') {
            if let Some((name, tail)) = rest.split_once('\'') {
                let list: Vec<String> = if tail.contains("does not depend on any axioms") {
                    vec![]
                } else if let Some(i) = tail.find('[') {
                    tail[i + 1..].trim_end_matches(']').split(',').map(|a| a.trim().to_string()).filter(|a| !a.is_empty()).collect()
                } else {
                    continue;
                };
                for a in &list {
                    if !ALLOWED_AXIOMS.contains(&a.as_str()) {
                        bad.push(format!("{name}: {a}"));
                    }
                }
                axioms.push((name.to_string(), list));
            }
        }
    }
    let ok = out.status.success() && bad.is_empty() && !log.contains("error:");
    Ok(KernelResult { ok, log, axioms, bad_axioms: bad })
}
